---
- name: Use different mongod.conf for auth initialization
  ansible.builtin.template:
    src: mongod_init.conf.j2
    dest: /etc/mongod.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - mongodb restart
    - wait when mongodb is started on localhost

- name: Flush all handlers at this point
  ansible.builtin.meta: flush_handlers

- name: Create administrative user "{{ mongodb_root_admin_name }}"
  community.mongodb.mongodb_user:
    database: admin
    name: "{{ mongodb_root_admin_name }}"
    password: "{{ mongodb_root_admin_password}}"
    roles: root
    update_password: "{{ mongodb_user_update_password }}"
    login_host: "{{ mongodb_net_bindip.split(',') | map('replace', '0.0.0.0', '127.0.0.1') | list  | first }}"
  no_log: true

- name: Move back mongod.conf
  ansible.builtin.template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - mongodb restart
    - wait when mongodb is started

- name: Flush all handlers at this point
  ansible.builtin.meta: flush_handlers
